#FROM node:20-slim
#
#WORKDIR /app
#
#RUN npm install -g @modelcontextprotocol/inspector
#
## Script d'entrée
#COPY entrypoint.sh /entrypoint.sh
#RUN chmod +x /entrypoint.sh
#
#EXPOSE 6274
#EXPOSE 6277
#
#ENTRYPOINT ["/entrypoint.sh"]
